### ISSUE TITLE
Outbound link decoder and IPv6 address

### ISSUE THREAD

**Issue by pulsarice** [alireza0/x-ui#1085] opened 2024-03-12 15:05 UTC
In "xray configs" when I want to add an outbound config using vless link when the address is an IPv6, I get the error "Wrong Link!"

`vless://uuid@[IPv6]:port?type=...`
note that I have put the IPv6 in brackets.

**Comment by alireza0** [comment] 2024-03-12 17:24
Dear @pulsarice ,

Please describe it more! It should works fine. Try : `vless://uuid@[IPv6]:1234?type=none`
1. Without proper evidences of investigation nobody can help you!
2. Make sure that you have found a BUG and root cause and probably a solution, then raise a BUG issue.

Thank you in advance

**Comment by MJamshidnejad** [comment] 2024-03-12 19:08
> Please try this exact link It gives error!
> 
> `vless://uuid@[2a00:1450:4001:810::200e]:1234?type=none`
> 
> ![image](https://private-user-images.githubusercontent.com/5326305/312182943-6fef598a-8c90-4599-91a4-8b1532f765e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzA3MTEsIm5iZiI6MTcxMDI3MDQxMSwicGF0aCI6Ii81MzI2MzA1LzMxMjE4Mjk0My02ZmVmNTk4YS04YzkwLTQ1OTktOTFhNC04YjE1MzJmNzY1ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTkwNjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAwODZjZDQ1YmUwOGZiNjVjNDY3OTQ2YmE0NjUxMjMxNGFjZDUzYWNlNDVhMzAzNDg0MTBmOTc1ZWVmYzk4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t3RKxD1CMaYZZVsj1KoIzmdl8aBQre-lxIC18TiZQro)

Remove the brackets and try again.

**Comment by alireza0** [comment] 2024-03-12 19:18
It is about regex I used for detecting the link. I am trying to support IPv6 as well.

**Comment by alireza0** [comment] 2024-03-12 19:23
It is fixed now and will be available in next release

**Closed** 2024-03-12 21:06 UTC
Labels: bug
