### ISSUE TITLE
Base64 is not encryption.

### ISSUE THREAD

**Issue by X-Oracle** [alireza0/x-ui#767] opened 2023-12-15 19:59 UTC
As you know `base64` is an encoding type. it should not be misunderstood as an `encryption` method.

So, I think it should be renamed as `Encode configs` instead of `Encrypt configs`.

Good Luck!

**Comment by alireza0** [comment] 2023-12-15 23:30
You are right. But it is not a bug. It is a kind of typo ;)

**Comment by alireza0** [comment] 2023-12-16 20:09
It is fixed in #765 by @shahin-io

**Comment by X-Oracle** [comment] 2023-12-17 11:55
Thank.

**Closed** 2023-12-17 11:55 UTC
Labels: bug
